Add support for keystone v3
internap/vagrant-openstack-cloud-provider pull request #4
Opened 2018-11-22 23:15 UTC by fbouliane

This will allow variables to passtrough the plugin and be relayed to
fog. Fog 1.0.3 doesn't seems to work well with keystonev2 so we dont
bump for now, further migration will be needed to support this version.

The plugin will still support a vagrant file that was working with v2
for now.

2018-11-23 14:02 UTC, lindycoder approved these changes

2018-11-23 14:03 UTC, lindycoder reviewed
internal comments

2018-11-23 14:04 UTC, lindycoder requested changes
internal comments

2018-11-23 16:25 UTC, fbouliane commented
Added support for autocompletion of keystonev2 urls
Identity version should be a string or int such as 3, '2.0'
user_domain => user_domain_name
project_domain => project_domain_name

And improved test coverage

2018-11-26 14:05 UTC, lindycoder approved these changes

2018-11-28 15:54 UTC, simon-begin approved these changes

2018-11-28 15:55 UTC, merged